### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [53]:
import numpy as np

In [11]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [17]:
array = np.diag(np.arange(5), k=0)
array

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [16]:
array.sum()

10

### Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [54]:
import pandas as pd
data = pd.read_csv('ratings.csv')
data.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [60]:
data.groupby(['movieId', 'rating']).count().sort_values('userId', ascending=False).head()


userId  timestamp
movieId rating                   
318     5.0        153        153
296     5.0        123        123
356     5.0        116        116
2571    5.0        109        109
260     5.0        104        104

### Задание 4
По данным файла power.csv посчитайте суммарное потребление стран прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [92]:
data = pd.read_csv('power.csv')
data.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [94]:
filtered_countries = data[ (data['country']=='Estonia') | (data['country']=='Lithuania') | (data['country']=='Latvia' ) ]

In [95]:
len(filtered_countries)

27306

In [96]:
filtered_countries = filtered_countries[ (filtered_countries['year'] >= 2005) | (filtered_countries['year'] <= 2010) ]

In [97]:
filtered_countries = filtered_countries[ (filtered_countries['category'] == 4) | (filtered_countries['category'] == 12) | (filtered_countries['category'] == 21) ]

In [98]:
filtered_countries[ (filtered_countries['quantity'] > 0) ].sum()

country     EstoniaEstoniaEstoniaEstoniaEstoniaEstoniaEsto...
year                                                  2092350
quantity                                             970728.0
category                                                18373
dtype: object

### Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [18]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [19]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [20]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True